server:
  port: 7030
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://61.164.246.80:3306/sq_tgwhn10832?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: sq_tgwhn10832
      password: xDmjsK9695
#      url: jdbc:mysql://43.247.68.242:3306/sq_852351851?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: sq_852351851
#      password: puhVCE3195
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    mp的日志开启
  global-config:
    db-config:
      id-type: ASSIGN_ID
LingaDawu:
    path: /java/img/